# Generated by Django 4.0 on 2022-01-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='/mypics/default.jpg', null=True, upload_to='mypics/'),
        ),
    ]
