# Generated by Django 4.0 on 2022-01-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('-created',)},
        ),
    ]
